quarkus:
  package:
    type: fast-jar
  swagger-ui:
    always-include: true
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/distribution_coursework
  flyway:
    migrate-at-start: true
  hibernate-orm:
    log:
      sql: false
  http:
    port: 8080

'%dev':
  quarkus:
    http:
      port: 8095